kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-olm-operator-role
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    capability.openshift.io/name: "OperatorLifecycleManagerV1"
    release.openshift.io/feature-set: TechPreviewNoUpgrade
subjects:
- kind: ServiceAccount
  name: cluster-olm-operator
  namespace: openshift-cluster-olm-operator
roleRef:
  kind: ClusterRole
  name: cluster-olm-operator
