apiVersion: v1
kind: Namespace
metadata:
  name: openshift-cluster-olm-operator
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    workload.openshift.io/allowed: "management"
    release.openshift.io/feature-set: TechPreviewNoUpgrade
