apiVersion: config.openshift.io/v1
kind: ClusterOperator
metadata:
  name: olm
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    capability.openshift.io/name: "OperatorLifecycleManagerV1"
    release.openshift.io/feature-set: TechPreviewNoUpgrade
spec: {}
status:
  versions:
  - name: operator
    version: "0.0.1-snapshot"
  relatedObjects:
  - group: ""
    name: openshift-cluster-olm-operator
    resource: namespaces
  - group: operator.openshift.io
    name: cluster
    resource: olms
