apiVersion: config.openshift.io/v1
kind: ClusterOperator
metadata:
  name: olm
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    release.openshift.io/feature-set: TechPreviewNoUpgrade
spec: {}
status:
  versions:
  - name: operator
    version: "0.0.1-snapshot"
